while True:
    raise Exception("Exception")